In [2]:
import os
import json
import pandas as pd

RUTA_RAW = os.path.join("data", "raw")

def diagnosticar_csv(nombre_archivo, separador=','):
    """Inspecciona estructura, columnas y tipos leyendo solo 500 filas."""
    ruta = os.path.join(RUTA_RAW, nombre_archivo)
    if not os.path.exists(ruta):
        print(f"AVISO: No se encontró {nombre_archivo}")
        return
        
    print("=" * 70)
    print(f"ARCHIVO: {nombre_archivo}")
    print("=" * 70)
    
    # 1. Leemos muestra controlada
    df_muestra = pd.read_csv(ruta, sep=separador, nrows=500)
    
    print("\n--- 1. INFORMACIÓN TÉCNICA (df.info()) ---")
    df_muestra.info()
    
    print("\n--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---")
    print(df_muestra.isnull().sum())
    
    print("\n--- 3. MUESTRA DE FILAS (df.head(2)) ---")
    display(df_muestra.head(2))

def diagnosticar_json(nombre_archivo, max_lineas=2):
    """Inspecciona archivos JSON Lines línea a línea sin saturar RAM."""
    ruta = os.path.join(RUTA_RAW, nombre_archivo)
    if not os.path.exists(ruta):
        print(f"AVISO: No se encontró {nombre_archivo}")
        return

    print("=" * 70)
    print(f"ARCHIVO JSON: {nombre_archivo}")
    print("=" * 70)
    
    muestras = []
    with open(ruta, 'r', encoding='utf-8') as f:
        for i, linea in enumerate(f):
            if i >= max_lineas:
                break
            muestras.append(json.loads(linea))
            
    df_json = pd.DataFrame(muestras)
    print("\n--- INFORMACIÓN TÉCNICA (df.info()) ---")
    df_json.info()
    display(df_json.head(2))

In [3]:
# --- Fuentes Crudas (Interacciones y Metadatos) ---
diagnosticar_csv("all_kindle_review .csv")
diagnosticar_csv("ratings_Beauty.csv")
diagnosticar_csv("Amazon_Beauty_Recommendation.csv")
diagnosticar_csv("Books_rating.csv")
diagnosticar_csv("books_data.csv")
diagnosticar_csv("amazon-fashion-800k+-user-reviews-dataset.csv")

diagnosticar_json("Video_Games_5.json")
diagnosticar_json("Electronics_5.json")

# --- Archivos derivados / procesados ---
diagnosticar_csv("preprocessed_kindle_review .csv")
diagnosticar_csv("interacciones.csv")
diagnosticar_csv("productos.csv")
diagnosticar_csv("resenas.csv")
diagnosticar_csv("resenas_traducidas.csv")

======================================================================
ARCHIVO: all_kindle_review .csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    500 non-null    int64
 1   Unnamed: 0      500 non-null    int64
 2   asin            500 non-null    str
 3   helpful         500 non-null    str
 4   rating          500 non-null    int64
 5   reviewText      500 non-null    str
 6   reviewTime      500 non-null    str
 7   reviewerID      500 non-null    str
 8   reviewerName    497 non-null    str
 9   summary         500 non-null    str
 10  unixReviewTime  500 non-null    int64
dtypes: int64(4), str(7)
memory usage: 363.1 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
Unnamed: 0.1      0
Unnamed: 0        0
asin              0
helpful           0
rating            0
reviewText        0
reviewTime        0
reviewerID        0
reviewerName      3
summary           0
unixReviewTime    0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400

======================================================================
ARCHIVO: ratings_Beauty.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   UserId     500 non-null    str
 1   ProductId  500 non-null    str
 2   Rating     500 non-null    float64
 3   Timestamp  500 non-null    int64
dtypes: float64(1), int64(1), str(2)
memory usage: 27.4 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
UserId       0
ProductId    0
Rating       0
Timestamp    0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

           UserId   ProductId  Rating   Timestamp
0  A39HTATAQ9V7YF  0205616461     5.0  1369699200
1  A3JM6GV9MNOF9X  0558925278     3.0  1355443200

======================================================================
ARCHIVO: Amazon_Beauty_Recommendation.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UserId       500 non-null    str
 1   ProductId    500 non-null    str
 2   ProductType  500 non-null    str
 3   Rating       500 non-null    int64
 4   Timestamp    500 non-null    int64
 5   URL          500 non-null    str
dtypes: int64(2), str(4)
memory usage: 105.4 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
UserId         0
ProductId      0
ProductType    0
Rating         0
Timestamp      0
URL            0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,UserId,ProductId,ProductType,Rating,Timestamp,URL
0,A3NHUQ33CFH3VM,B00LLPT4HI,Eyeliner & Kajal,5,1405814400,https://www.amazon.in/Maybelline-Colossal-Kaja...
1,A1TIRNQ7O4REOH,B00LLPT4HI,Eyeliner & Kajal,4,1405987200,https://www.amazon.in/Maybelline-Colossal-Kaja...

======================================================================
ARCHIVO: Books_rating.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  500 non-null    str
 1   Title               500 non-null    str
 2   Price               130 non-null    float64
 3   User_id             369 non-null    str
 4   profileName         369 non-null    str
 5   review/helpfulness  500 non-null    str
 6   review/score        500 non-null    float64
 7   review/time         500 non-null    int64
 8   review/summary      500 non-null    str
 9   review/text         500 non-null    str
dtypes: float64(2), int64(1), str(7)
memory usage: 445.4 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
Id                      0
Title                   0
Price                 370
User_id               131
profileName           131
review/helpfulness      0
review/score            0
review/time             0
review/summary          0
review/text             0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...

======================================================================
ARCHIVO: books_data.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          500 non-null    str
 1   description    351 non-null    str
 2   authors        457 non-null    str
 3   image          387 non-null    str
 4   previewLink    478 non-null    str
 5   publisher      327 non-null    str
 6   publishedDate  472 non-null    str
 7   infoLink       478 non-null    str
 8   categories     414 non-null    str
 9   ratingsCount   124 non-null    float64
dtypes: float64(1), str(9)
memory usage: 457.1 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
Title              0
description      149
authors           43
image            113
previewLink       22
publisher        173
publishedDate     28
infoLink          22
categories        86
ratingsCount     376
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,Title,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,Its Only Art If Its Well Hung!,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN

======================================================================
ARCHIVO: amazon-fashion-800k+-user-reviews-dataset.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rating              500 non-null    float64
 1   title               500 non-null    str
 2   text                500 non-null    str
 3   images              500 non-null    str
 4   asin                500 non-null    str
 5   parent_asin         500 non-null    str
 6   user_id             500 non-null    str
 7   timestamp           500 non-null    int64
 8   helpful_vote        500 non-null    int64
 9   verified_purchases  500 non-null    bool
 10  target              500 non-null    int64
dtypes: bool(1), float64(1), int64(3), str(6)
memory usage: 160.5 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
rating                0
title                 0
text                  0
images                0
asin                  0
parent_asin           0
user_id               0
timestamp             0
helpful_vote          0
verified_purchases    0
target                0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchases,target
0,1.0,It say 5 pair when purchasing but only get 2 r...,I was looking for 5 pair and only received 2 p...,[],B07QFTMTLP,B07QFTMTLP,AHASEZ65RESN57BMGRV6QBM5DTIA,1565088068852,0,True,-1
1,1.0,DonÃ¢ÂÂt do it!,Just donÃ¢ÂÂt. These things fell apart after...,[],B0764KKDN1,B0764KKDN1,AE3AMA3QSOHFKV46JJAHTHMMIR6A,1622416429592,0,True,-1

======================================================================
ARCHIVO JSON: Video_Games_5.json
======================================================================

--- INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   overall         2 non-null      float64
 1   verified        2 non-null      bool
 2   reviewTime      2 non-null      str
 3   reviewerID      2 non-null      str
 4   asin            2 non-null      str
 5   reviewerName    2 non-null      str
 6   reviewText      2 non-null      str
 7   summary         2 non-null      str
 8   unixReviewTime  2 non-null      int64
dtypes: bool(1), float64(1), int64(1), str(6)
memory usage: 787.0 bytes

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime
0,5.0,True,"10 17, 2015",A1HP7NVNPFMA4N,0700026657,Ambrosia075,"This game is a bit hard to get the hang of, bu...",but when you do it's great.,1445040000
1,4.0,False,"07 27, 2015",A1JGAP0185YJI6,0700026657,travis,I played it a while but it was alright. The st...,"But in spite of that it was fun, I liked it",1437955200

======================================================================
ARCHIVO JSON: Electronics_5.json
======================================================================

--- INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      2 non-null      str
 1   asin            2 non-null      str
 2   reviewerName    2 non-null      str
 3   helpful         2 non-null      object
 4   reviewText      2 non-null      str
 5   overall         2 non-null      float64
 6   summary         2 non-null      str
 7   unixReviewTime  2 non-null      int64
 8   reviewTime      2 non-null      str
dtypes: float64(1), int64(1), object(1), str(6)
memory usage: 3.3+ KB

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5.0,Gotta have GPS!,1370131200,"06 2, 2013"
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1.0,Very Disappointed,1290643200,"11 25, 2010"

======================================================================
ARCHIVO: preprocessed_kindle_review .csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  500 non-null    int64
 1   rating      500 non-null    int64
 2   reviewText  500 non-null    str
 3   summary     500 non-null    str
dtypes: int64(2), str(2)
memory usage: 301.3 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
Unnamed: 0    0
rating        0
reviewText    0
summary       0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,Unnamed: 0,rating,reviewText,summary
0,0,5,This book was the very first bookmobile book I...,50 + years ago...
1,1,1,"When I read the description for this book, I c...",Boring! Boring! Boring!

======================================================================
ARCHIVO: interacciones.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     500 non-null    str
 1   product_id  500 non-null    str
 2   rating      500 non-null    float64
 3   fecha       500 non-null    str
 4   texto       500 non-null    str
dtypes: float64(1), str(4)
memory usage: 145.7 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
user_id       0
product_id    0
rating        0
fecha         0
texto         0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,user_id,product_id,rating,fecha,texto
0,AE23AFEWCE57EGSGOSLMOW46GFIA,az_B01G4PLDYG,5.0,2017-02-02,Thumbs up. Exactly what I wanted: loose harem ...
1,AE23AFEWCE57EGSGOSLMOW46GFIA,az_B07CQ84KLT,1.0,2021-07-23,NOT. Iâ€™ve been sewing for 50 years and this ...

======================================================================
ARCHIVO: productos.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       500 non-null    str
 1   titulo           500 non-null    str
 2   tienda           450 non-null    str
 3   precio           65 non-null     float64
 4   rating_promedio  500 non-null    float64
 5   numero_resenas   500 non-null    int64
 6   texto_producto   500 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 216.7 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
product_id           0
titulo               0
tienda              50
precio             435
rating_promedio      0
numero_resenas       0
texto_producto       0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,product_id,titulo,tienda,precio,rating_promedio,numero_resenas,texto_producto
0,az_1574998102,Compact 1 Reading Glasses - Tortoise +3.00,Nannini,NaN,5.0,1,Compact 1 Reading Glasses - Tortoise +3.00. no...
1,az_6152004349,freeband Fullmetal Alchemist Cosplay Costume A...,freeband,NaN,4.0,35,freeband Fullmetal Alchemist Cosplay Costume A...

======================================================================
ARCHIVO: resenas.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            500 non-null    str
 1   product_id         500 non-null    str
 2   rating             500 non-null    int64
 3   fecha              500 non-null    str
 4   titulo_resena      500 non-null    str
 5   texto_resena       500 non-null    str
 6   texto              500 non-null    str
 7   compra_verificada  500 non-null    bool
dtypes: bool(1), int64(1), str(6)
memory usage: 379.3 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
user_id              0
product_id           0
rating               0
fecha                0
titulo_resena        0
texto_resena         0
texto                0
compra_verificada    0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,user_id,product_id,rating,fecha,titulo_resena,texto_resena,texto,compra_verificada
0,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,az_B00LOPVX74,5,2020-01-09,Pretty locket,I think this locket is really pretty. The insi...,Pretty locket. I think this locket is really p...,True
1,AFVNEEPDEIH5SPUN5BWC6NKL3WNQ,az_B07F2BTFS9,1,2018-12-31,Wonâ€™t buy again,Crappy socks. Money wasted. Bought to wear wit...,Wonâ€™t buy again. Crappy socks. Money wasted....,True

======================================================================
ARCHIVO: resenas_traducidas.csv
======================================================================

--- 1. INFORMACIÓN TÉCNICA (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idx_muestra       500 non-null    int64
 1   user_id           500 non-null    str
 2   product_id        500 non-null    str
 3   rating            500 non-null    int64
 4   fecha             500 non-null    str
 5   texto             500 non-null    str
 6   texto_es          500 non-null    str
 7   texto_lematizado  498 non-null    str
 8   sentimiento       500 non-null    float64
dtypes: float64(1), int64(2), str(6)
memory usage: 236.9 KB

--- 2. CONTEO DE VALORES NULOS (df.isnull().sum()) ---
idx_muestra         0
user_id             0
product_id          0
rating              0
fecha               0
texto               0
texto_es            0
texto_lematizado    2
sentimiento         0
dtype: int64

--- 3. MUESTRA DE FILAS (df.head(2)) ---

,idx_muestra,user_id,product_id,rating,fecha,texto,texto_es,texto_lematizado,sentimiento
0,0,AH3WD272ZPZR4NNZIR6PPWMWH4EA,az_B009YDTDUC,5,2013-10-14,Wonderful. I bought this to complete my son's ...,Maravilloso. Compré esto para completar el tra...,maravilloso comprar completar traje novia hijo...,1.0
1,1,AH3FJKZ3CTC7TM5FJ7TNUGIRAQ5A,az_B01G4TEVYG,5,2017-08-03,Five Stars. Love it!!,Cinco estrellas. ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡...,estrella,0.0